//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerStartOrStop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerStartOrStop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 boxName 的本地化字符串。
        /// </summary>
        internal static string Form1_AddBtt_boxName {
            get {
                return ResourceManager.GetString("Form1_AddBtt_boxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 txtName 的本地化字符串。
        /// </summary>
        internal static string Form1_AddLab_txtName {
            get {
                return ResourceManager.GetString("Form1_AddLab_txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 txtSatus 的本地化字符串。
        /// </summary>
        internal static string Form1_AddLab_txtSatus {
            get {
                return ResourceManager.GetString("Form1_AddLab_txtSatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服务 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_停止服务 {
            get {
                return ResourceManager.GetString("Form1_Init_停止服务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动服务 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_启动服务 {
            get {
                return ResourceManager.GetString("Form1_Init_启动服务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务即将暂停 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务即将暂停 {
            get {
                return ResourceManager.GetString("Form1_Init_服务即将暂停", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务即将继续 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务即将继续 {
            get {
                return ResourceManager.GetString("Form1_Init_服务即将继续", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务已暂停 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务已暂停 {
            get {
                return ResourceManager.GetString("Form1_Init_服务已暂停", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务未运行 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务未运行 {
            get {
                return ResourceManager.GetString("Form1_Init_服务未运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务正在停止 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务正在停止 {
            get {
                return ResourceManager.GetString("Form1_Init_服务正在停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务正在启动 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务正在启动 {
            get {
                return ResourceManager.GetString("Form1_Init_服务正在启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务正在运行 的本地化字符串。
        /// </summary>
        internal static string Form1_Init_服务正在运行 {
            get {
                return ResourceManager.GetString("Form1_Init_服务正在运行", resourceCulture);
            }
        }
    }
}
